"""empty message

Revision ID: 228411380f5a
Revises: 173f65394bb6
Create Date: 2017-07-23 15:58:33.955513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228411380f5a'
down_revision = '173f65394bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Player Dates',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], )
    )
    op.drop_table('user')
    op.drop_table('User Dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User Dates',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Player Dates')
    op.drop_table('player')
    # ### end Alembic commands ###
